#! /bin/bash

# === Configuration

TARGET_FS=/path/to/target/filesystem/mountpoint
SRC_DIR=/path/to/your/original/files
DST_DIR=/path/to/backup/location

LOG_AGENT=prefix-for-log-and-backup-file
LOG_DIR=/path/to/logs/directory
INTERVAL=1month

# === Script body

LOG=$LOG_DIR/$LOG_AGENT-$(date "+%Y%m%d").log
gzip $LOG_DIR/$LOG_AGENT-$(date -d -$INTERVAL "+%Y%m%d").log

date >> $LOG
echo "" >> $LOG

mountpoint -q $TARGET_FS
if [[ $? -ne 0 ]]; then
    echo "ERROR: $TARGET_FS is not mounted!" >> $LOG
    exit 1
fi

tar -vcz -f $DST_DIR/$LOG_AGENT-$(date "+%Y%m%d").tgz $SRC_DIR >> $LOG

echo "" >> $LOG
date >> $LOG
